# Analyze Temporal Feature Signal

Диагностика признаков из `adausdt_minute_log_return_temporal_dataset.parquet`:

- baseline модель на time split;
- permutation importance;
- mutual information;
- autocorrelation target/features;
- SHAP, если установлен пакет `shap`.

Датасет большой, поэтому анализ работает на равномерном sample по parquet row groups. Это быстрее и достаточно для первого feature screening.

In [3]:
from pathlib import Path
import json
import math
import warnings

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

from sklearn.ensemble import ExtraTreesRegressor, HistGradientBoostingRegressor
from sklearn.feature_selection import mutual_info_regression
from sklearn.impute import SimpleImputer
from sklearn.inspection import permutation_importance
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.pipeline import make_pipeline

warnings.filterwarnings("ignore", category=UserWarning)
pd.set_option("display.max_columns", 120)
pd.set_option("display.max_rows", 120)
pd.set_option("display.max_colwidth", 160)

try:
    display
except NameError:
    display = print

## Settings

In [4]:
DATASET_PATH = Path("model_artifacts/adausdt_minute_log_return_temporal_dataset.parquet")
REPORT_PATH = Path("model_artifacts/temporal_feature_signal_report.json")

TARGET_COL = "log_return_1m"
NON_FEATURE_COLS = {"date", "timestamp", "log_return_1m", "return_1m"}

# Keep the first pass intentionally compact. Increase these after the first read.
SAMPLE_ROWS = 250_000
MODEL_FEATURE_LIMIT = 350
PERMUTATION_FEATURE_LIMIT = 80
MI_FEATURE_LIMIT = 250
SHAP_BACKGROUND_ROWS = 2_000
SHAP_EXPLAIN_ROWS = 5_000

RANDOM_STATE = 42
TRAIN_FRACTION = 0.8
ACF_LAGS = [1, 2, 3, 5, 10, 15, 30, 60, 120]

assert DATASET_PATH.exists(), DATASET_PATH

## Schema And Column Selection

In [5]:
pf = pq.ParquetFile(DATASET_PATH)
all_columns = pf.schema_arrow.names
feature_cols = [col for col in all_columns if col not in NON_FEATURE_COLS]

print("rows", pf.metadata.num_rows)
print("row_groups", pf.num_row_groups)
print("columns", len(all_columns))
print("feature_columns", len(feature_cols))

display(pd.Series(feature_cols).head(30).to_frame("feature"))

rows 3157859
row_groups 4
columns 404
feature_columns 400

                                     feature
0           aggression_features__V_buy_quote
1          aggression_features__V_sell_quote
2       aggression_features__delta_base_norm
3      aggression_features__delta_quote_norm
4               btc_features__btc_log_return
5       btc_features__btc_rolling_volatility
6                   btc_features__btc_zscore
7      intraminute_dynamics__F_concentration
8                   intraminute_dynamics__RV
9   intraminute_dynamics__pressure_segment_3
10      intraminute_dynamics__pressure_total
11           intraminute_features__body_norm
12     intraminute_features__taker_buy_ratio
13     intraminute_features__wick_lower_norm
14     intraminute_features__wick_upper_norm
15         intraminute_segments__VWAP_minute
16      intraminute_segments__VWAP_segment_1
17      intraminute_segments__VWAP_segment_2
18      intraminute_segments__VWAP_segment_3
19                      price_pressure__F_PI
20               price_pressure__F_asymmetry
21                     price_pressure__F_eff
22                  price_pressure__PI_total
23                  price_pressure__VWAP_pos
24                 sinthetic_data__asia_open
25                  sinthetic_data__cos_hour
26               sinthetic_data__cos_weekday
27               sinthetic_data__europe_open
28                  sinthetic_data__sin_hour
29               sinthetic_data__sin_weekday

Для модели сначала ограничим число фичей: берём все фичи, но если их слишком много, ранжируем по variance на маленьком sample и оставляем самые вариативные. Это не финальный отбор, а способ сделать первый анализ быстрым.

In [6]:
def sample_parquet_rows(columns, sample_rows=SAMPLE_ROWS, random_state=RANDOM_STATE):
    rng = np.random.default_rng(random_state)
    per_group = max(1, math.ceil(sample_rows / pf.num_row_groups))
    parts = []
    for group_idx in range(pf.num_row_groups):
        table = pf.read_row_group(group_idx, columns=columns)
        part = table.to_pandas()
        if len(part) > per_group:
            idx = np.sort(rng.choice(len(part), size=per_group, replace=False))
            part = part.iloc[idx]
        parts.append(part)
    out = pd.concat(parts, ignore_index=True)
    if "timestamp" in out.columns:
        out["timestamp"] = pd.to_datetime(out["timestamp"], utc=True)
        out = out.sort_values("timestamp").reset_index(drop=True)
    if len(out) > sample_rows:
        keep = np.linspace(0, len(out) - 1, sample_rows).round().astype(int)
        out = out.iloc[keep].reset_index(drop=True)
    return out


small_cols = ["timestamp", TARGET_COL] + feature_cols
small_sample_rows = min(80_000, SAMPLE_ROWS)
small = sample_parquet_rows(small_cols, sample_rows=small_sample_rows)
variances = small[feature_cols].var(numeric_only=True).sort_values(ascending=False)
model_feature_cols = variances.head(min(MODEL_FEATURE_LIMIT, len(variances))).index.tolist()

print("small sample", small.shape)
print("selected model features", len(model_feature_cols))
display(variances.head(30).to_frame("variance"))

small sample (72131, 402)
selected model features 350

                                               variance
price_pressure__F_asymmetry__roll_std_30   3.727453e+23
price_pressure__F_asymmetry__roll_std_15   2.021167e+23
price_pressure__F_asymmetry__lag_3         5.835260e+22
price_pressure__F_asymmetry__lag_5         4.081229e+22
price_pressure__F_asymmetry__lag_10        3.305857e+22
price_pressure__F_asymmetry__roll_mean_15  1.462419e+22
price_pressure__F_asymmetry__roll_mean_30  1.312181e+22
price_pressure__F_asymmetry__roll_std_5    1.122993e+22
price_pressure__F_asymmetry__ewm_mean_30   4.776429e+21
price_pressure__F_asymmetry__lag_1         4.512992e+21
price_pressure__F_asymmetry__roll_mean_5   2.830789e+21
price_pressure__F_asymmetry__lag_2         2.577484e+21
price_pressure__F_asymmetry__ewm_mean_15   2.561983e+21
price_pressure__F_asymmetry                1.328783e+21
price_pressure__F_asymmetry__ewm_mean_5    1.174124e+21
aggression_features__V_sell_quote__lag_2   2.578588e+11
aggression_features__V_sell_quote__lag_1   2.024356e+11
aggression_features__V_buy_quote__lag_1    1.819129e+11
aggression_features__V_sell_quote__lag_30  1.566294e+11
aggression_features__V_sell_quote__lag_10  1.454581e+11
aggression_features__V_sell_quote__lag_15  1.446468e+11
aggression_features__V_sell_quote__lag_3   1.374840e+11
aggression_features__V_sell_quote          1.359157e+11
aggression_features__V_sell_quote__lag_5   1.299467e+11
aggression_features__V_buy_quote__lag_2    1.262162e+11
aggression_features__V_buy_quote__lag_30   1.223648e+11
aggression_features__V_buy_quote           1.188298e+11
aggression_features__V_buy_quote__lag_5    1.126883e+11
aggression_features__V_buy_quote__lag_3    1.118813e+11
aggression_features__V_buy_quote__lag_10   1.102405e+11

## Load Analysis Sample

In [7]:
analysis_cols = ["date", "timestamp", TARGET_COL] + model_feature_cols
data = sample_parquet_rows(analysis_cols, sample_rows=SAMPLE_ROWS)
data = data.dropna(subset=[TARGET_COL]).reset_index(drop=True)

print(data.shape)
print(data["timestamp"].min(), data["timestamp"].max())
display(data[["date", "timestamp", TARGET_COL]].head())
display(data[["date", "timestamp", TARGET_COL]].tail())

(199631, 353)
2020-02-01 01:01:00+00:00 2026-02-01 23:59:00+00:00

         date                 timestamp  log_return_1m
0  2020-02-01 2020-02-01 01:01:00+00:00       0.000000
1  2020-02-01 2020-02-01 01:04:00+00:00       0.001839
2  2020-02-01 2020-02-01 01:14:00+00:00       0.000000
3  2020-02-01 2020-02-01 01:20:00+00:00       0.002018
4  2020-02-01 2020-02-01 01:44:00+00:00      -0.000367

              date                 timestamp  log_return_1m
199626  2026-02-01 2026-02-01 23:55:00+00:00       0.000700
199627  2026-02-01 2026-02-01 23:56:00+00:00       0.001399
199628  2026-02-01 2026-02-01 23:57:00+00:00      -0.002099
199629  2026-02-01 2026-02-01 23:58:00+00:00       0.000350
199630  2026-02-01 2026-02-01 23:59:00+00:00       0.001050

## Baseline Model

In [8]:
split_idx = int(len(data) * TRAIN_FRACTION)
train = data.iloc[:split_idx].copy()
test = data.iloc[split_idx:].copy()

X_train = train[model_feature_cols]
y_train = train[TARGET_COL]
X_test = test[model_feature_cols]
y_test = test[TARGET_COL]

model = make_pipeline(
    SimpleImputer(strategy="median"),
    HistGradientBoostingRegressor(
        max_iter=250,
        learning_rate=0.04,
        max_leaf_nodes=31,
        l2_regularization=0.0,
        random_state=RANDOM_STATE,
    ),
)
model.fit(X_train, y_train)
pred = model.predict(X_test)

baseline_metrics = {
    "train_rows": int(len(X_train)),
    "test_rows": int(len(X_test)),
    "train_end": str(train["timestamp"].max()),
    "test_start": str(test["timestamp"].min()),
    "mae": float(mean_absolute_error(y_test, pred)),
    "rmse": float(mean_squared_error(y_test, pred) ** 0.5),
    "r2": float(r2_score(y_test, pred)),
    "directional_accuracy": float((np.sign(pred) == np.sign(y_test)).mean()),
}
baseline_metrics

{'train_rows': 159704,
 'test_rows': 39927,
 'train_end': '2025-03-06 20:47:00+00:00',
 'test_start': '2025-03-06 21:09:00+00:00',
 'mae': 0.000798354087354718,
 'rmse': 0.001296106015318484,
 'r2': 0.009901866546654592,
 'directional_accuracy': 0.44248253061837856}

## Permutation Importance

In [9]:
perm_feature_cols = model_feature_cols[:PERMUTATION_FEATURE_LIMIT]
perm_rows = min(50_000, len(X_test))
X_perm = X_test[perm_feature_cols].tail(perm_rows)
y_perm = y_test.tail(perm_rows)

# Refit a smaller model on the same feature subset to make permutation faster and more interpretable.
perm_model = make_pipeline(
    SimpleImputer(strategy="median"),
    HistGradientBoostingRegressor(max_iter=180, learning_rate=0.05, max_leaf_nodes=31, random_state=RANDOM_STATE),
)
perm_model.fit(X_train[perm_feature_cols], y_train)

perm = permutation_importance(
    perm_model,
    X_perm,
    y_perm,
    n_repeats=5,
    random_state=RANDOM_STATE,
    scoring="neg_mean_squared_error",
    n_jobs=1,
)
permutation_importance_df = (
    pd.DataFrame({
        "feature": perm_feature_cols,
        "importance_mean": perm.importances_mean,
        "importance_std": perm.importances_std,
    })
    .sort_values("importance_mean", ascending=False)
    .reset_index(drop=True)
)
display(permutation_importance_df.head(50))

,feature,importance_mean,importance_std
0,price_pressure__F_PI__roll_std_15,8.842112e-09,2.905101e-10
1,intraminute_dynamics__pressure_segment_3__roll_max_5,5.306659e-09,2.897429e-10
2,price_pressure__F_PI__roll_mean_15,2.457185e-09,7.909453e-10
3,intraminute_dynamics__pressure_segment_3__roll_mean_5,2.350986e-09,0.000000e+00
4,trade_distribution__N_eff_buy__roll_sum_60,2.204466e-09,6.153216e-11
5,price_pressure__F_PI__ewm_mean_5,1.865799e-09,1.468753e-09
6,price_pressure__F_asymmetry__ewm_mean_5,1.678876e-09,3.197012e-10
7,intraminute_dynamics__F_concentration,1.600583e-09,6.097073e-10
8,aggression_features__V_buy_quote__lag_10,1.447987e-09,0.000000e+00
9,intraminute_dynamics__pressure_total__roll_max_5,1.197012e-09,3.341136e-11
10,price_pressure__F_asymmetry__roll_mean_15,9.600647e-10,5.044907e-10
11,aggression_features__V_sell_quote__lag_10,9.249762e-10,2.972703e-11
12,intraminute_dynamics__F_concentration__roll_std_5,7.698493e-10,3.964936e-10
13,price_pressure__PI_total__lag_1,6.630482e-10,2.085442e-10
14,price_pressure__F_asymmetry__lag_10,6.589671e-10,3.278308e-10
15,trade_distribution__N_eff_buy__roll_sum_30,6.282463e-10,0.000000e+00
16,price_pressure__F_PI__roll_mean_30,5.862619e-10,3.806246e-10
17,price_pressure__F_asymmetry__lag_2,4.808105e-10,8.993633e-10
18,intraminute_dynamics__F_concentration__roll_max_30,4.458618e-10,5.121142e-10
19,price_pressure__PI_total__roll_std_5,4.274766e-10,1.582750e-11
20,price_pressure__F_PI__lag_5,3.974046e-10,1.987023e-10
21,intraminute_dynamics__pressure_total__roll_std_30,3.937610e-10,0.000000e+00
22,aggression_features__V_sell_quote__lag_5,3.905932e-10,0.000000e+00
23,price_pressure__F_PI__roll_mean_5,3.317631e-10,1.431999e-10
24,intraminute_dynamics__F_concentration__roll_mean_30,3.299253e-10,5.768353e-10
25,intraminute_dynamics__F_concentration__roll_std_30,2.421613e-10,4.843226e-10
26,price_pressure__F_PI__lag_2,2.196800e-10,4.784940e-10
27,intraminute_dynamics__F_concentration__roll_mean_15,2.066132e-10,8.209142e-10
28,trade_distribution__N_eff_sell__roll_sum_15,1.799710e-10,0.000000e+00
29,price_pressure__F_asymmetry__roll_mean_5,1.485965e-10,1.335211e-10
30,aggression_features__V_buy_quote__lag_3,1.437067e-10,4.182867e-10
31,aggression_features__V_buy_quote__lag_15,1.239129e-10,2.456269e-11
32,aggression_features__V_buy_quote__lag_1,9.808595e-11,3.958945e-10
33,price_pressure__F_PI__roll_std_30,6.841630e-11,0.000000e+00
34,price_pressure__F_asymmetry__lag_5,4.758222e-11,5.683944e-11
35,intraminute_dynamics__F_concentration__roll_max_5,3.977304e-11,8.395397e-10
36,price_pressure__F_asymmetry__ewm_mean_30,2.174759e-11,1.798637e-10
37,price_pressure__PI_total__roll_std_30,0.000000e+00,0.000000e+00
38,price_pressure__F_asymmetry__roll_std_5,0.000000e+00,0.000000e+00
39,price_pressure__F_asymmetry__ewm_mean_15,0.000000e+00,0.000000e+00
40,price_pressure__F_asymmetry__roll_std_15,0.000000e+00,0.000000e+00
41,price_pressure__PI_total__roll_std_15,0.000000e+00,0.000000e+00
42,intraminute_dynamics__pressure_total__roll_std_5,0.000000e+00,0.000000e+00
43,trade_distribution__N_eff_buy__roll_sum_15,0.000000e+00,0.000000e+00
44,intraminute_dynamics__pressure_total__roll_max_15,0.000000e+00,0.000000e+00
45,price_pressure__F_PI__roll_std_5,0.000000e+00,0.000000e+00
46,aggression_features__V_buy_quote__lag_2,0.000000e+00,0.000000e+00
47,aggression_features__V_sell_quote__lag_15,0.000000e+00,0.000000e+00
48,intraminute_dynamics__F_concentration__roll_std_15,0.000000e+00,0.000000e+00
49,trade_distribution__N_eff_sell__roll_sum_60,0.000000e+00,0.000000e+00

## Mutual Information

In [10]:
mi_feature_cols = model_feature_cols[:MI_FEATURE_LIMIT]
mi_rows = min(80_000, len(data))
mi_data = data.tail(mi_rows).copy()

mi_imputer = SimpleImputer(strategy="median")
X_mi = mi_imputer.fit_transform(mi_data[mi_feature_cols])
y_mi = mi_data[TARGET_COL].to_numpy()

mi_values = mutual_info_regression(X_mi, y_mi, random_state=RANDOM_STATE, n_neighbors=5)
mutual_info_df = (
    pd.DataFrame({"feature": mi_feature_cols, "mutual_information": mi_values})
    .sort_values("mutual_information", ascending=False)
    .reset_index(drop=True)
)
display(mutual_info_df.head(50))

                                                   feature  mutual_information
0                     intraminute_segments__VWAP_segment_3            2.937079
1                        intraminute_segments__VWAP_minute            2.884121
2                     intraminute_segments__VWAP_segment_2            2.872194
3                     intraminute_segments__VWAP_segment_1            2.811921
4        intraminute_dynamics__pressure_total__roll_max_30            0.190977
5    intraminute_dynamics__pressure_segment_3__roll_max_30            0.188005
6               trade_distribution__N_eff_buy__roll_sum_60            0.170182
7              trade_distribution__N_eff_buy__roll_mean_60            0.170182
8              trade_distribution__N_eff_sell__roll_sum_60            0.165175
9             trade_distribution__N_eff_sell__roll_mean_60            0.165175
10   intraminute_dynamics__pressure_segment_3__roll_std_30            0.164190
11                   price_pressure__PI_total__roll_std_30            0.161787
12       intraminute_dynamics__pressure_total__roll_std_30            0.161785
13             trade_distribution__N_eff_buy__roll_mean_30            0.161292
14              trade_distribution__N_eff_buy__roll_sum_30            0.161292
15             trade_distribution__N_eff_buy__roll_mean_15            0.152867
16              trade_distribution__N_eff_buy__roll_sum_15            0.152867
17             trade_distribution__N_eff_sell__roll_sum_30            0.150964
18            trade_distribution__N_eff_sell__roll_mean_30            0.150964
19   intraminute_dynamics__pressure_segment_3__roll_max_15            0.144500
20             trade_distribution__N_eff_sell__roll_std_60            0.143079
21             trade_distribution__N_eff_sell__roll_sum_15            0.141922
22            trade_distribution__N_eff_sell__roll_mean_15            0.141922
23                             sinthetic_data__sin_weekday            0.141621
24       intraminute_dynamics__pressure_total__roll_max_15            0.141173
25              trade_distribution__N_eff_buy__roll_std_60            0.140431
26                   price_pressure__PI_total__roll_std_15            0.140105
27       intraminute_dynamics__pressure_total__roll_std_15            0.140100
28       aggression_features__delta_base_norm__roll_std_60            0.136927
29      aggression_features__delta_quote_norm__roll_std_60            0.136730
30   intraminute_dynamics__pressure_segment_3__roll_std_15            0.135969
31   aggression_features__delta_base_norm__roll_abs_sum_60            0.129871
32  aggression_features__delta_quote_norm__roll_abs_sum_60            0.129560
33                             sinthetic_data__cos_weekday            0.127335
34              trade_distribution__N_eff_buy__roll_std_30            0.123004
35       trades_minute_level__delta_base_norm__roll_std_30            0.121117
36       aggression_features__delta_base_norm__roll_std_30            0.120832
37      trades_minute_level__delta_quote_norm__roll_std_30            0.120819
38      aggression_features__delta_quote_norm__roll_std_30            0.120382
39             trade_distribution__N_eff_sell__roll_std_30            0.115425
40  aggression_features__delta_quote_norm__roll_abs_sum_30            0.115393
41   aggression_features__delta_base_norm__roll_abs_sum_30            0.115089
42  intraminute_dynamics__pressure_segment_3__roll_mean_30            0.110857
43      trades_minute_level__delta_quote_norm__roll_std_15            0.109973
44        intraminute_dynamics__pressure_total__roll_std_5            0.109791
45                    price_pressure__PI_total__roll_std_5            0.109790
46       trades_minute_level__delta_base_norm__roll_std_15            0.109577
47      aggression_features__delta_quote_norm__roll_std_15            0.109241
48       aggression_features__delta_base_norm__roll_std_15            0.108782
49    intraminute_dynamics__pressure_segment_3__roll_std_5            0.106547

## Autocorrelation

In [11]:
# Target autocorrelation on the full target column, narrow read.
target_only = pd.read_parquet(DATASET_PATH, columns=["timestamp", TARGET_COL])
target_only["timestamp"] = pd.to_datetime(target_only["timestamp"], utc=True)
target_only = target_only.sort_values("timestamp").reset_index(drop=True)

target_acf_df = pd.DataFrame(
    [{"lag": lag, "target_autocorrelation": float(target_only[TARGET_COL].autocorr(lag=lag))} for lag in ACF_LAGS]
)
display(target_acf_df)

# Feature autocorrelation for union of top permutation and MI features.
top_features = list(dict.fromkeys(
    permutation_importance_df.head(25)["feature"].tolist()
    + mutual_info_df.head(25)["feature"].tolist()
))
feature_acf_rows = []
for col in top_features:
    for lag in [1, 5, 15, 60]:
        feature_acf_rows.append({"feature": col, "lag": lag, "autocorrelation": float(data[col].autocorr(lag=lag))})
feature_acf_df = pd.DataFrame(feature_acf_rows).sort_values(["lag", "autocorrelation"], ascending=[True, False])
display(feature_acf_df.head(80))

   lag  target_autocorrelation
0    1                0.007905
1    2               -0.014879
2    3               -0.000492
3    5               -0.001258
4   10                0.006179
5   15                0.009430
6   30                0.005731
7   60                0.006445
8  120                0.004293

,feature,lag,autocorrelation
104,intraminute_segments__VWAP_minute,1,0.999858
180,sinthetic_data__sin_weekday,1,0.999806
112,intraminute_segments__VWAP_segment_1,1,0.999795
108,intraminute_segments__VWAP_segment_2,1,0.999719
100,intraminute_segments__VWAP_segment_3,1,0.999691
124,trade_distribution__N_eff_buy__roll_mean_60,1,0.964736
16,trade_distribution__N_eff_buy__roll_sum_60,1,0.964736
128,trade_distribution__N_eff_sell__roll_sum_60,1,0.964063
132,trade_distribution__N_eff_sell__roll_mean_60,1,0.964063
60,trade_distribution__N_eff_buy__roll_sum_30,1,0.923418
144,trade_distribution__N_eff_buy__roll_mean_30,1,0.923418
156,trade_distribution__N_eff_sell__roll_sum_30,1,0.921952
160,trade_distribution__N_eff_sell__roll_mean_30,1,0.921952
168,trade_distribution__N_eff_sell__roll_std_60,1,0.904936
64,price_pressure__F_PI__roll_mean_30,1,0.871740
148,trade_distribution__N_eff_buy__roll_mean_15,1,0.865821
152,trade_distribution__N_eff_buy__roll_sum_15,1,0.865821
176,trade_distribution__N_eff_sell__roll_mean_15,1,0.863701
172,trade_distribution__N_eff_sell__roll_sum_15,1,0.863701
0,price_pressure__F_PI__roll_std_15,1,0.780897
84,intraminute_dynamics__pressure_total__roll_std_30,1,0.719529
140,price_pressure__PI_total__roll_std_30,1,0.719529
8,price_pressure__F_PI__roll_mean_15,1,0.717633
136,intraminute_dynamics__pressure_segment_3__roll_std_30,1,0.706633
116,intraminute_dynamics__pressure_total__roll_max_30,1,0.697221
120,intraminute_dynamics__pressure_segment_3__roll_max_30,1,0.696459
96,intraminute_dynamics__F_concentration__roll_mean_30,1,0.653729
72,intraminute_dynamics__F_concentration__roll_max_30,1,0.546887
32,aggression_features__V_buy_quote__lag_10,1,0.539882
88,aggression_features__V_sell_quote__lag_5,1,0.508127
44,aggression_features__V_sell_quote__lag_10,1,0.504537
36,intraminute_dynamics__pressure_total__roll_max_5,1,0.504021
76,price_pressure__PI_total__roll_std_5,1,0.466501
20,price_pressure__F_PI__ewm_mean_5,1,0.409133
92,price_pressure__F_PI__roll_mean_5,1,0.407012
12,intraminute_dynamics__pressure_segment_3__roll_mean_5,1,0.358511
4,intraminute_dynamics__pressure_segment_3__roll_max_5,1,0.269850
164,intraminute_dynamics__pressure_segment_3__roll_max_15,1,0.227195
184,intraminute_dynamics__pressure_total__roll_max_15,1,0.221241
52,price_pressure__PI_total__lag_1,1,0.181516
80,price_pressure__F_PI__lag_5,1,0.088061
40,price_pressure__F_asymmetry__roll_mean_15,1,0.060325
24,price_pressure__F_asymmetry__ewm_mean_5,1,0.057156
48,intraminute_dynamics__F_concentration__roll_std_5,1,0.003101
28,intraminute_dynamics__F_concentration,1,0.000687
56,price_pressure__F_asymmetry__lag_10,1,-0.002546
68,price_pressure__F_asymmetry__lag_2,1,-0.003975
105,intraminute_segments__VWAP_minute,5,0.999538
113,intraminute_segments__VWAP_segment_1,5,0.999473
109,intraminute_segments__VWAP_segment_2,5,0.999401
101,intraminute_segments__VWAP_segment_3,5,0.999368
181,sinthetic_data__sin_weekday,5,0.998361
125,trade_distribution__N_eff_buy__roll_mean_60,5,0.786118
17,trade_distribution__N_eff_buy__roll_sum_60,5,0.786118
129,trade_distribution__N_eff_sell__roll_sum_60,5,0.782979
133,trade_distribution__N_eff_sell__roll_mean_60,5,0.782979
145,trade_distribution__N_eff_buy__roll_mean_30,5,0.708076
61,trade_distribution__N_eff_buy__roll_sum_30,5,0.708076
161,trade_distribution__N_eff_sell__roll_mean_30,5,0.705176
157,trade_distribution__N_eff_sell__roll_sum_30,5,0.705176
65,price_pressure__F_PI__roll_mean_30,5,0.700709
1,price_pressure__F_PI__roll_std_15,5,0.656632
149,trade_distribution__N_eff_buy__roll_mean_15,5,0.645809
153,trade_distribution__N_eff_buy__roll_sum_15,5,0.645809
173,trade_distribution__N_eff_sell__roll_sum_15,5,0.643862
177,trade_distribution__N_eff_sell__roll_mean_15,5,0.643862
169,trade_distribution__N_eff_sell__roll_std_60,5,0.583485
9,price_pressure__F_PI__roll_mean_15,5,0.557156
33,aggression_features__V_buy_quote__lag_10,5,0.361908
89,aggression_features__V_sell_quote__lag_5,5,0.337891
45,aggression_features__V_sell_quote__lag_10,5,0.331506
93,price_pressure__F_PI__roll_mean_5,5,0.327296
21,price_pressure__F_PI__ewm_mean_5,5,0.325789
13,intraminute_dynamics__pressure_segment_3__roll_mean_5,5,0.150261
77,price_pressure__PI_total__roll_std_5,5,0.141435
37,intraminute_dynamics__pressure_total__roll_max_5,5,0.136172
141,price_pressure__PI_total__roll_std_30,5,0.097122
85,intraminute_dynamics__pressure_total__roll_std_30,5,0.097122
81,price_pressure__F_PI__lag_5,5,0.082865
5,intraminute_dynamics__pressure_segment_3__roll_max_5,5,0.082416

## SHAP

Если `shap` не установлен, установи его в окружение и перезапусти этот блок:

```powershell
python -m pip install shap
```

In [12]:
shap_importance_df = pd.DataFrame(columns=["feature", "mean_abs_shap"])

try:
    import shap

    shap_feature_cols = perm_feature_cols
    shap_model = ExtraTreesRegressor(
        n_estimators=120,
        min_samples_leaf=30,
        max_features=0.7,
        random_state=RANDOM_STATE,
        n_jobs=1,
    )
    shap_imputer = SimpleImputer(strategy="median")
    X_shap_train = shap_imputer.fit_transform(X_train[shap_feature_cols].tail(min(120_000, len(X_train))))
    y_shap_train = y_train.tail(min(120_000, len(y_train))).to_numpy()
    shap_model.fit(X_shap_train, y_shap_train)

    X_explain = shap_imputer.transform(X_test[shap_feature_cols].tail(min(SHAP_EXPLAIN_ROWS, len(X_test))))
    explainer = shap.TreeExplainer(shap_model)
    shap_values = explainer.shap_values(X_explain, check_additivity=False)
    shap_importance_df = (
        pd.DataFrame({
            "feature": shap_feature_cols,
            "mean_abs_shap": np.abs(shap_values).mean(axis=0),
        })
        .sort_values("mean_abs_shap", ascending=False)
        .reset_index(drop=True)
    )
    display(shap_importance_df.head(50))
except ModuleNotFoundError as exc:
    print("SHAP skipped:", exc)
    print("Install with: python -m pip install shap")

c:\Users\Пользователь\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

                                                  feature  mean_abs_shap
0    intraminute_dynamics__pressure_segment_3__roll_std_5       0.000005
1        intraminute_dynamics__pressure_total__roll_max_5       0.000004
2                   price_pressure__PI_total__roll_std_15       0.000004
3                       aggression_features__V_sell_quote       0.000004
4       intraminute_dynamics__pressure_total__roll_max_15       0.000004
5    intraminute_dynamics__pressure_segment_3__roll_max_5       0.000004
6       intraminute_dynamics__pressure_total__roll_max_30       0.000004
7                    price_pressure__PI_total__roll_std_5       0.000004
8        intraminute_dynamics__pressure_total__roll_std_5       0.000004
9                aggression_features__V_sell_quote__lag_2       0.000004
10  intraminute_dynamics__pressure_segment_3__roll_std_15       0.000003
11      intraminute_dynamics__pressure_total__roll_std_30       0.000003
12                  price_pressure__PI_total__roll_std_30       0.000003
13  intraminute_dynamics__pressure_segment_3__roll_mean_5       0.000003
14                      price_pressure__F_PI__roll_std_15       0.000003
15                        price_pressure__PI_total__lag_1       0.000003
16  intraminute_dynamics__pressure_segment_3__roll_max_30       0.000003
17                        price_pressure__PI_total__lag_2       0.000003
18             trade_distribution__N_eff_buy__roll_sum_60       0.000003
19            trade_distribution__N_eff_sell__roll_sum_60       0.000003
20            trade_distribution__N_eff_sell__roll_sum_15       0.000003
21                        price_pressure__PI_total__lag_3       0.000003
22               aggression_features__V_sell_quote__lag_3       0.000003
23  intraminute_dynamics__pressure_segment_3__roll_max_15       0.000003
24                       aggression_features__V_buy_quote       0.000003
25            trade_distribution__N_eff_sell__roll_sum_30       0.000003
26                aggression_features__V_buy_quote__lag_2       0.000003
27               aggression_features__V_buy_quote__lag_10       0.000002
28             trade_distribution__N_eff_buy__roll_sum_15       0.000002
29                aggression_features__V_buy_quote__lag_3       0.000002
30              aggression_features__V_sell_quote__lag_15       0.000002
31               aggression_features__V_sell_quote__lag_1       0.000002
32  intraminute_dynamics__pressure_segment_3__roll_std_30       0.000002
33                      price_pressure__F_PI__roll_std_30       0.000002
34                aggression_features__V_buy_quote__lag_1       0.000002
35              aggression_features__V_sell_quote__lag_10       0.000002
36                aggression_features__V_buy_quote__lag_5       0.000002
37                       price_pressure__F_PI__roll_std_5       0.000002
38             trade_distribution__N_eff_buy__roll_sum_30       0.000002
39              aggression_features__V_sell_quote__lag_30       0.000002
40               aggression_features__V_buy_quote__lag_15       0.000002
41               aggression_features__V_buy_quote__lag_30       0.000002
42                           price_pressure__F_PI__lag_10       0.000002
43               aggression_features__V_sell_quote__lag_5       0.000001
44                     price_pressure__F_PI__roll_mean_30       0.000001
45               price_pressure__F_asymmetry__roll_std_30       0.000001
46                      price_pressure__F_PI__ewm_mean_30       0.000001
47                            price_pressure__F_PI__lag_3       0.000001
48                     price_pressure__F_PI__roll_mean_15       0.000001
49                      price_pressure__F_PI__ewm_mean_15       0.000001

## Combined Ranking And Save

In [13]:
combined = pd.DataFrame({"feature": sorted(set(
    permutation_importance_df["feature"].tolist()
    + mutual_info_df["feature"].tolist()
    + shap_importance_df["feature"].tolist()
))})
combined = combined.merge(permutation_importance_df, on="feature", how="left")
combined = combined.merge(mutual_info_df, on="feature", how="left")
combined = combined.merge(shap_importance_df, on="feature", how="left")

for metric in ["importance_mean", "mutual_information", "mean_abs_shap"]:
    if metric in combined.columns:
        rank_col = f"{metric}_rank"
        combined[rank_col] = combined[metric].rank(ascending=False, method="average", na_option="bottom")

rank_cols = [col for col in combined.columns if col.endswith("_rank")]
combined["average_rank"] = combined[rank_cols].mean(axis=1)
combined_ranking_df = combined.sort_values("average_rank").reset_index(drop=True)
display(combined_ranking_df.head(80))

out_dir = Path("model_artifacts/feature_signal")
out_dir.mkdir(parents=True, exist_ok=True)
permutation_importance_df.to_csv(out_dir / "permutation_importance.csv", index=False)
mutual_info_df.to_csv(out_dir / "mutual_information.csv", index=False)
target_acf_df.to_csv(out_dir / "target_autocorrelation.csv", index=False)
feature_acf_df.to_csv(out_dir / "feature_autocorrelation.csv", index=False)
shap_importance_df.to_csv(out_dir / "shap_importance.csv", index=False)
combined_ranking_df.to_csv(out_dir / "combined_feature_ranking.csv", index=False)

report = {
    "dataset": str(DATASET_PATH),
    "sample_rows": int(len(data)),
    "model_feature_count": int(len(model_feature_cols)),
    "baseline_metrics": baseline_metrics,
    "top_permutation": permutation_importance_df.head(30).to_dict(orient="records"),
    "top_mutual_information": mutual_info_df.head(30).to_dict(orient="records"),
    "target_autocorrelation": target_acf_df.to_dict(orient="records"),
    "top_shap": shap_importance_df.head(30).to_dict(orient="records"),
    "output_dir": str(out_dir),
}
REPORT_PATH.write_text(json.dumps(report, indent=2), encoding="utf-8")
print(f"saved report: {REPORT_PATH}")
print(f"saved csv files: {out_dir}")

,feature,importance_mean,importance_std,mutual_information,mean_abs_shap,importance_mean_rank,mutual_information_rank,mean_abs_shap_rank,average_rank
0,trade_distribution__N_eff_buy__roll_sum_60,2.204466e-09,6.153216e-11,0.170182,2.862185e-06,5.0,7.0,19.0,10.333333
1,intraminute_dynamics__pressure_total__roll_std_30,3.937610e-10,0.000000e+00,0.161785,3.280355e-06,22.0,13.0,12.0,15.666667
2,intraminute_dynamics__pressure_total__roll_max_30,0.000000e+00,0.000000e+00,0.190977,4.076199e-06,46.0,5.0,7.0,19.333333
3,intraminute_dynamics__pressure_total__roll_max_5,1.197012e-09,3.341136e-11,0.099504,4.483001e-06,10.0,56.0,2.0,22.666667
4,intraminute_dynamics__pressure_segment_3__roll_max_30,0.000000e+00,0.000000e+00,0.188005,2.955144e-06,46.0,6.0,17.0,23.000000
5,intraminute_dynamics__pressure_segment_3__roll_max_5,5.306659e-09,2.897429e-10,0.094422,4.222035e-06,2.0,62.0,6.0,23.333333
6,trade_distribution__N_eff_buy__roll_sum_30,6.282463e-10,0.000000e+00,0.161292,1.998840e-06,16.0,15.0,39.0,23.333333
7,price_pressure__PI_total__roll_std_30,0.000000e+00,0.000000e+00,0.161787,3.175956e-06,46.0,12.0,13.0,23.666667
8,trade_distribution__N_eff_sell__roll_sum_15,1.799710e-10,0.000000e+00,0.141922,2.787115e-06,29.0,22.0,21.0,24.000000
9,price_pressure__PI_total__roll_std_5,4.274766e-10,1.582750e-11,0.109790,3.890917e-06,20.0,46.0,8.0,24.666667
10,trade_distribution__N_eff_sell__roll_sum_60,0.000000e+00,0.000000e+00,0.165175,2.819651e-06,46.0,9.0,20.0,25.000000
11,price_pressure__PI_total__roll_std_15,0.000000e+00,0.000000e+00,0.140105,4.380129e-06,46.0,27.0,3.0,25.333333
12,intraminute_dynamics__pressure_total__roll_max_15,0.000000e+00,0.000000e+00,0.141173,4.246021e-06,46.0,25.0,5.0,25.333333
13,trade_distribution__N_eff_buy__roll_sum_15,0.000000e+00,0.000000e+00,0.152867,2.448617e-06,46.0,17.0,29.0,30.666667
14,intraminute_dynamics__pressure_segment_3__roll_std_5,0.000000e+00,0.000000e+00,0.106547,5.038135e-06,46.0,50.0,1.0,32.333333
15,intraminute_dynamics__pressure_segment_3__roll_std_30,-2.584009e-12,0.000000e+00,0.164190,2.321432e-06,55.0,11.0,33.0,33.000000
16,intraminute_dynamics__pressure_segment_3__roll_mean_5,2.350986e-09,0.000000e+00,0.075406,3.037356e-06,4.0,81.0,14.0,33.000000
17,intraminute_dynamics__pressure_total__roll_std_5,0.000000e+00,0.000000e+00,0.109791,3.823145e-06,46.0,45.0,9.0,33.333333
18,intraminute_dynamics__pressure_segment_3__roll_max_15,-2.802899e-11,0.000000e+00,0.144500,2.676585e-06,57.0,20.0,24.0,33.666667
19,trade_distribution__N_eff_sell__roll_sum_30,-1.890992e-10,0.000000e+00,0.150964,2.649013e-06,63.0,18.0,26.0,35.666667
20,intraminute_dynamics__pressure_segment_3__roll_std_15,-6.557649e-10,7.010493e-11,0.135969,3.335419e-06,70.0,31.0,11.0,37.333333
21,aggression_features__V_buy_quote__lag_10,1.447987e-09,0.000000e+00,0.081328,2.480564e-06,9.0,76.0,28.0,37.666667
22,price_pressure__F_PI__roll_std_15,8.842112e-09,2.905101e-10,0.058776,3.016896e-06,1.0,103.0,15.0,39.666667
23,price_pressure__PI_total__lag_1,6.630482e-10,2.085442e-10,0.061405,2.986603e-06,14.0,96.0,16.0,42.000000
24,aggression_features__V_buy_quote__lag_3,1.437067e-10,4.182867e-10,0.089768,2.427947e-06,31.0,66.0,30.0,42.333333
25,aggression_features__V_buy_quote__lag_1,9.808595e-11,3.958945e-10,0.096452,2.131816e-06,33.0,60.0,35.0,42.666667
26,aggression_features__V_sell_quote__lag_10,9.249762e-10,2.972703e-11,0.078245,2.127284e-06,12.0,80.0,36.0,42.666667
27,aggression_features__V_sell_quote,-1.196684e-09,0.000000e+00,0.098762,4.365391e-06,76.0,57.0,4.0,45.666667
28,aggression_features__V_buy_quote__lag_2,0.000000e+00,0.000000e+00,0.092535,2.540193e-06,46.0,64.0,27.0,45.666667
29,aggression_features__V_sell_quote__lag_5,3.905932e-10,0.000000e+00,0.085560,1.497645e-06,23.0,72.0,44.0,46.333333
30,aggression_features__V_sell_quote__lag_3,0.000000e+00,0.000000e+00,0.084223,2.706421e-06,46.0,73.0,23.0,47.333333
31,aggression_features__V_buy_quote,-9.015210e-10,1.698444e-10,0.104227,2.676436e-06,75.0,51.0,25.0,50.333333
32,aggression_features__V_buy_quote__lag_15,1.239129e-10,2.456269e-11,0.081019,1.775123e-06,32.0,78.0,41.0,50.333333
33,price_pressure__F_PI__roll_mean_30,5.862619e-10,3.806246e-10,0.064502,1.454784e-06,17.0,91.0,45.0,51.000000
34,aggression_features__V_sell_quote__lag_15,0.000000e+00,0.000000e+00,0.081310,2.414365e-06,46.0,77.0,31.0,51.333333
35,aggression_features__V_sell_quote__lag_2,-8.851865e-10,4.789909e-10,0.086520,3.771526e-06,74.0,71.0,10.0,51.666667
36,price_pressure__F_PI__roll_std_30,6.841630e-11,0.000000e+00,0.065763,2.280588e-06,34.0,89.0,34.0,52.333333
37,aggression_features__V_sell_quote__lag_1,-2.613108e-10,0.000000e+00,0.093735,2.368388e-06,65.0,63.0,32.0,53.333333
38,intraminute_dynamics__F_concentration__roll_max_30,4.458618e-10,5.121142e-10,0.064917,2.872050e-07,19.0,90.0,60.0,56.333333
39,price_pressure__F_PI__roll_mean_15,2.457185e-09,7.909453e-10,0.051008,1.392626e-06,3.0,122.0,49.0,58.000000
40,aggression_features__V_buy_quote__lag_5,-2.285285e-09,3.030934e-10,0.089692,2.060330e-06,78.0,69.0,37.0,61.333333
41,aggression_features__V_buy_quote__lag_30,-5.902219e-11,5.980212e-11,0.073678,1.757411e-06,60.0,82.0,42.0,61.333333
42,price_pressure__PI_total__lag_3,-4.161521e-11,0.000000e+00,0.056564,2.761220e-06,58.0,108.0,22.0,62.666667
43,price_pressure__F_PI__ewm_mean_5,1.865799e-09,1.468753e-09,0.035598,1.124972e-06,6.0,135.0,55.0,65.333333
44,aggression_features__V_sell_quote__lag_30,-6.816126e-10,0.000000e+00,0.073254,1.828686e-06,72.0,85.0,40.0,65.666667
45,price_pressure__F_PI__ewm_mean_30,-3.137993e-10,1.568997e-10,0.066833,1.418959e-06,66.0,88.0,47.0,67.000000
46,intraminute_dynamics__F_concentration__roll_std_30,2.421613e-10,4.843226e-10,0.052419,2.621487e-07,26.0,115.0,62.0,67.666667
47,price_pressure__PI_total__lag_2,-4.066087e-09,8.721868e-12,0.055541,2.952098e-06,80.0,111.0,18.0,69.666667
48,price_pressure__F_PI__roll_mean_5,3.317631e-10,1.431999e-10,0.034938,1.180693e-06,24.0,136.0,53.0,71.000000
49,price_pressure__F_PI__roll_std_5,0.000000e+00,0.000000e+00,0.037958,2.039244e-06,46.0,131.0,38.0,71.666667
50,price_pressure__F_asymmetry__roll_mean_15,9.600647e-10,5.044907e-10,0.027267,2.045156e-07,11.0,137.0,69.0,72.333333
51,intraminute_dynamics__F_concentration__roll_mean_30,3.299253e-10,5.768353e-10,0.025191,2.333613e-07,25.0,140.0,67.0,77.333333
52,price_pressure__F_PI__ewm_mean_15,-6.734823e-10,2.145881e-10,0.053793,1.368049e-06,71.0,113.0,50.0,78.000000
53,price_pressure__F_PI__lag_2,2.196800e-10,4.784940e-10,0.019448,1.210609e-06,27.0,165.0,52.0,81.333333
54,intraminute_dynamics__F_concentration__roll_std_15,0.000000e+00,0.000000e+00,0.024688,2.580855e-07,46.0,142.0,63.0,83.666667
55,price_pressure__F_PI__lag_5,3.974046e-10,1.987023e-10,0.014791,9.881695e-07,21.0,175.0,56.0,84.000000
56,price_pressure__F_asymmetry__roll_std_30,-8.307069e-10,1.382124e-09,0.025451,1.448805e-06,73.0,138.0,46.0,85.666667
57,intraminute_dynamics__F_concentration__roll_max_15,-4.102484e-10,2.880123e-10,0.037405,3.051114e-07,67.0,133.0,58.0,86.000000
58,intraminute_dynamics__F_concentration__roll_mean_15,2.066132e-10,8.209142e-10,0.017944,2.353614e-07,28.0,167.0,66.0,87.000000
59,price_pressure__F_asymmetry__roll_mean_30,-2.289485e-10,1.586227e-10,0.037775,2.004823e-07,64.0,132.0,70.0,88.666667
60,price_pressure__F_asymmetry__ewm_mean_30,2.174759e-11,1.798637e-10,0.017822,2.666683e-07,37.0,168.0,61.0,88.666667
61,intraminute_dynamics__F_concentration__roll_std_5,7.698493e-10,3.964936e-10,0.010434,2.956080e-07,13.0,199.0,59.0,90.333333
62,price_pressure__F_PI__lag_1,-5.485678e-10,3.368624e-10,0.021484,1.234830e-06,69.0,159.0,51.0,93.000000
63,price_pressure__F_PI,-1.331208e-10,7.803421e-11,0.015656,1.129952e-06,61.0,173.0,54.0,96.000000
64,price_pressure__F_asymmetry__ewm_mean_15,0.000000e+00,0.000000e+00,0.014992,2.100453e-07,46.0,174.0,68.0,96.000000
65,price_pressure__F_PI__lag_3,-2.395415e-09,4.165361e-09,0.019966,1.418309e-06,79.0,164.0,48.0,97.000000
66,intraminute_dynamics__F_concentration__roll_max_5,3.977304e-11,8.395397e-10,0.008947,3.083198e-07,36.0,202.0,57.0,98.333333
67,price_pressure__F_asymmetry__ewm_mean_5,1.678876e-09,3.197012e-10,0.006661,1.666517e-07,7.0,215.0,74.0,98.666667
68,price_pressure__F_PI__lag_10,-1.257149e-09,1.594453e-09,0.013703,1.556802e-06,77.0,179.0,43.0,99.666667
69,price_pressure__F_asymmetry__roll_mean_5,1.485965e-10,1.335211e-10,0.009556,1.895371e-07,30.0,200.0,72.0,100.666667
70,intraminute_dynamics__F_concentration,1.600583e-09,6.097073e-10,0.000000,2.526023e-07,8.0,246.0,64.0,106.000000
71,price_pressure__F_asymmetry__lag_2,4.808105e-10,8.993633e-10,0.000361,1.719637e-07,18.0,239.0,73.0,110.000000
72,intraminute_segments__VWAP_segment_3,NaN,NaN,2.937079,NaN,165.5,1.0,165.5,110.666667
73,intraminute_segments__VWAP_minute,NaN,NaN,2.884121,NaN,165.5,2.0,165.5,111.000000
74,intraminute_segments__VWAP_segment_2,NaN,NaN,2.872194,NaN,165.5,3.0,165.5,111.333333
75,intraminute_segments__VWAP_segment_1,NaN,NaN,2.811921,NaN,165.5,4.0,165.5,111.666667
76,price_pressure__F_asymmetry__lag_10,6.589671e-10,3.278308e-10,0.000000,1.130018e-07,15.0,246.0,78.0,113.000000
77,trade_distribution__N_eff_buy__roll_mean_60,NaN,NaN,0.170182,NaN,165.5,8.0,165.5,113.000000
78,trade_distribution__N_eff_sell__roll_mean_60,NaN,NaN,0.165175,NaN,165.5,10.0,165.5,113.666667
79,intraminute_dynamics__F_concentration__roll_mean_5,-4.647452e-11,9.294904e-11,0.005556,2.519963e-07,59.0,218.0,65.0,114.000000

saved report: model_artifacts\temporal_feature_signal_report.json
saved csv files: model_artifacts\feature_signal